### PR TITLE
Returns false instead of throwing an error

### PR DESCRIPTION
**Pull request by rafet-ongun**
When guid is not supplied for a guid bucketed feature, returns false instead of throwing an error. 

https://deliveroo.atlassian.net/browse/PROM-1156

### CODE REVIEW

**Review by adilh-d — APPROVED** [review]
LGTM as long as we get approval from the maintainers that the change of behaviour is acceptable

**Review by jphastings — COMMENTED** [review]
This makes sense. I originally had this as `error` because a GUID-bucketed feature that isn't given a GUID is _definitely_ a broken experiment/feature (there is never a reason to not have a GUID) — now there is a `notice_error` feature in [most implementations](https://github.com/deliveroo/determinator/blob/master/lib/determinator/control.rb#L136) I think we can raise the error _internally_ (so it's visible) but externally return `false`.

I've not yet approved though as you need to pump [the VERSION](https://github.com/deliveroo/determinator-standard-tests/blob/master/VERSION) as part of this PR (this change will be a minor bump, I think), so the various libraries can assert that they're built against the correct version of the standard tests 😊

**Comment by rafet-ongun** [comment]
> This makes sense. I originally had this as `error` because a GUID-bucketed feature that isn't given a GUID is _definitely_ a broken experiment/feature (there is never a reason to not have a GUID) — now there is a `notice_error` feature in [most implementations](https://github.com/deliveroo/determinator/blob/master/lib/determinator/control.rb#L136) I think we can raise the error _internally_ (so it's visible) but externally return `false`.
> 
> I've not yet approved though as you need to pump [the VERSION](https://github.com/deliveroo/determinator-standard-tests/blob/master/VERSION) as part of this PR (this change will be a minor bump, I think), so the various libraries can assert that they're built against the correct version of the standard tests 😊

The version have been bumped now 🙂

**Review by me — APPROVED** [review]
LGTM!

**Review by jphastings — APPROVED** [review]

**Pull request merged**
