### PR TITLE
Add tests for non-string variant values

### PR DESCRIPTION
**Pull request by tmarchant-roo**
We've had issues using the Go Determinator client - if constraint data is updated directly in Ruby console to use numeric values, the Go client is unable to parse them.

See examples below:

```
// String values (works)
"constraints": {
   "zone_id": ["1", "2", "3"]
}
```

```
// Numeric values (doesn't work, constraint is not parsed at all)
"constraints": {
   "zone_id": [1, 2, 3]
}
```

Perhaps this isn't meant to be supported, in which case we should amend `actor-tracking` code to prevent any non-string values being set in experiment data.

This PR adds a couple of tests to ensure clients are parsing numeric/boolean constraint values as strings.

See https://github.com/deliveroo/determinator-go/pull/33 for potential fix in the Go client. Haven't checked if it affects Ruby client as well

### CODE REVIEW

**Review by me — APPROVED** [review]
LGTM! 👍

**Comment by tmarchant-roo** [comment]
@me do I need to update the `VERSION` file in the root before I merge? or is that done automagically

**Comment by jphastings** [comment]
It almost certainly needs manual changes — automagic wasn't as easy when this was first created! :)

**Review by jphastings — APPROVED** [review]

**Comment by jphastings** [comment]
I like the defensiveness, but I also think we should update the Actor Tracking code to ensure only strings are ever allowed into the serialized messages.

**Comment by tmarchant-roo** [comment]
> I like the defensiveness, but I also think we should update the Actor Tracking code to ensure only strings are ever allowed into the serialized messages.

Agree that would be safer. But it might cause grief when updating existing experiments via the UI, if some variants already contain invalid data?

**Pull request merged**
